# Run from project root: make -f docker/Makefile build
build:
	docker build -f docker/Dockerfile -t bettercode .

# Or run from docker directory: make build-from-here
build-from-here:
	docker build -f Dockerfile -t bettercode ..
